-- Seed Data for RoleSync AI

-- 1. Insert HODs
INSERT INTO staff (id, full_name, email, password_hash, department, designation, contact, user_type, status)
VALUES
  ('00000000-0000-0000-0000-000000000001', 'Dr. Raghav Mehta', 'admin@rolesync.edu', 'password123', 'Computer Science', 'Head of Department', '+91-9876543210', 'Admin', 'Active'),
  ('00000000-0000-0000-0000-000000000102', 'Dr. Sunita Sharma', 'hod.mech@rolesync.edu', 'password123', 'Mechanical Engineering', 'Head of Department', '+91-9876543212', 'Admin', 'Active'),
  ('00000000-0000-0000-0000-000000000103', 'Dr. Arvind Verma', 'hod.ee@rolesync.edu', 'password123', 'Electrical Engineering', 'Head of Department', '+91-9876543213', 'Admin', 'Active')
ON CONFLICT (email) DO NOTHING;

-- 2. Insert Faculties
INSERT INTO staff (id, full_name, email, password_hash, department, designation, contact, user_type, status)
VALUES
  ('00000000-0000-0000-0000-000000000002', 'Devansh Sharma', 'faculty@rolesync.edu', 'password123', 'Computer Science', 'Assistant Professor', '+91-9876543211', 'Faculty', 'Leaving'),
  ('00000000-0000-0000-0000-000000000104', 'Anita Desai', 'anita.d@rolesync.edu', 'password123', 'Computer Science', 'Lab Administrator', '+91-9876543214', 'Faculty', 'Active'),
  ('00000000-0000-0000-0000-000000000105', 'Vikram Patel', 'vikram.p@rolesync.edu', 'password123', 'Mechanical Engineering', 'Associate Professor', '+91-9876543215', 'Faculty', 'Active')
ON CONFLICT (email) DO NOTHING;

-- 3. Insert Tasks for Faculty (Devansh Sharma - '00000000-0000-0000-0000-000000000002')
-- We need to look up task_category ids, but since they are UUIDs and generated by gen_random_uuid(), we can do it by name via subquery.

DO $$ 
DECLARE
  internship_cat_id UUID;
  teaching_cat_id UUID;
  exam_cat_id UUID;
BEGIN
  SELECT id INTO internship_cat_id FROM task_categories WHERE name = 'Internship Responsibility' LIMIT 1;
  SELECT id INTO teaching_cat_id FROM task_categories WHERE name = 'Subject Teaching' LIMIT 1;
  SELECT id INTO exam_cat_id FROM task_categories WHERE name = 'Examination Duty' LIMIT 1;

  INSERT INTO tasks (title, description, category_id, assigned_to, created_by, status, priority, deadline)
  VALUES
    ('Upload final semester grading sheets', 'Complete grading for CS-401 and upload to university portal.', exam_cat_id, '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Not Started', 'Urgent', CURRENT_DATE + INTERVAL '2 days'),
    ('Hand over current syllabus progress to HOD', 'Share the Google Drive link with all lecture notes for Database Systems.', teaching_cat_id, '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Done', 'High', CURRENT_DATE - INTERVAL '1 day'),
    ('Transfer list of active recruiting companies', 'TCS Placement MoU 2025 and Wipro onboarding contacts.', internship_cat_id, '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'In Progress', 'Medium', CURRENT_DATE + INTERVAL '5 days');
END $$;
